.TH "class_file" 3 "Sat May 16 2015" "Version 1.0" "libclass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class_file \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <class\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u4 \fBmagic\fP"
.br
.ti -1c
.RI "u2 \fBminor_version\fP"
.br
.ti -1c
.RI "u2 \fBmajor_version\fP"
.br
.ti -1c
.RI "u2 \fBconstant_pool_count\fP"
.br
.ti -1c
.RI "\fBcp_info\fP * \fBconstant_pool\fP"
.br
.ti -1c
.RI "u2 \fBaccess_flags\fP"
.br
.ti -1c
.RI "u2 \fBthis_class\fP"
.br
.ti -1c
.RI "u2 \fBsuper_class\fP"
.br
.ti -1c
.RI "u2 \fBinterfaces_count\fP"
.br
.ti -1c
.RI "u2 * \fBinterfaces\fP"
.br
.ti -1c
.RI "u2 \fBfields_count\fP"
.br
.ti -1c
.RI "\fBfield_info\fP * \fBfields\fP"
.br
.ti -1c
.RI "u2 \fBmethods_count\fP"
.br
.ti -1c
.RI "\fBmethod_info\fP * \fBmethods\fP"
.br
.ti -1c
.RI "u2 \fBattributes_count\fP"
.br
.ti -1c
.RI "\fBattribute_info\fP * \fBattributes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class_file_comment 

.SH "Author"
.PP 
Generated automatically by Doxygen for libclass from the source code\&.
