.TH "class.h" 3 "Sat May 16 2015" "Version 1.0" "libclass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcp_info\fP"
.br
.ti -1c
.RI "struct \fBfield_info\fP"
.br
.ti -1c
.RI "struct \fBmethod_info\fP"
.br
.ti -1c
.RI "struct \fBattribute_info\fP"
.br
.ti -1c
.RI "struct \fBclass_file\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libclass from the source code\&.
