.TH "js-simplify.h" 3 "Fri May 22 2015" "Version 1.0" "js-simplify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
js-simplify.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBjs_simplify\fP (char *input, char *output)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for js-simplify from the source code\&.
