.TH "list_head" 3 "Sat May 16 2015" "Version 1.0" "libclass" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_head \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct list * \fBprev\fP"
.br
.ti -1c
.RI "struct list * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class list head comment 

.SH "Author"
.PP 
Generated automatically by Doxygen for libclass from the source code\&.
